name: tests-orders

on:
  pull_request
    paths: #only run the test on auth when push request related to auth directory
      - "orders/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
