name: tests-tickets

on:
  pull_request:
    paths: #only run the test on tickets when push request related to tickets directory
      - "tickets/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
