name: tests-payments

on:
  pull_request:
    paths: #only run the test on payments when push request related to payments directory
      - "payments/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
